project:
  type: book
  output-dir: _book

book:
  title: "Think Like A Physicist"
  author:
    - Casey Handmer
    - Jonathan Whitmore
  date: "2025"
  image: cover.png
  sidebar:
    logo: physics_logo.png
    search: true
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - thinking.qmd
        - math.qmd
    - part: "Classical Physics"
      chapters:
        - mechanics.qmd
        - thermo.qmd
        - waves.qmd
    - part: "Electromagnetism & Optics"
      chapters:
        - electrostatics.qmd
        - circuits.qmd
        - optics.qmd
    - part: "Modern Physics"
      chapters:
        - relativity.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt
